cloud:
  aws:
    credentials:
      access-key: AKIAYNOK6RHHVMN2B4OY
      secret-key: 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
    region:
      static: ap-northeast-1
      auto: false
      stack:
        auto: false